import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs'
import path from 'path'
import os from 'os'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

function copyToPluginsPlugin() {
	return {
		name: 'copy-to-plugins',
		setup(build) {
			build.onEnd(async () => {
				const sourceDir = process.cwd()
				const destDir = path.join(
					os.homedir(),
					'obsidian',
					'.obsidian',
					'plugins',
					'digest'
				)
				await fs.promises.mkdir(destDir, { recursive: true })
				for (const file of ['main.js', 'manifest.json', 'styles.css']) {
					const src = path.join(sourceDir, file)
					const dst = path.join(destDir, file)
					try {
						await fs.promises.copyFile(src, dst)
					} catch (err) {
						console.error(`Error copying ${file}: ${err}`)
					}
				}
				console.log(`Copied to ${destDir}`)
			})
		}
	}
}

const context = await esbuild.context({
	platform: 'node',
	banner: { js: banner },
	entryPoints: [{ in: 'src/obsidian.ts', out: 'main' }],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: './',
	plugins: [copyToPluginsPlugin()]
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
