import builtins from 'builtin-modules'
import esbuild from 'esbuild'
import process from 'process'
import fs from 'fs'
import path from 'path'
import os from 'os'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

function copyToPluginsPlugin() {
	const destDir = path.join(os.homedir(), 'obsidian', '.obsidian', 'plugins', 'enzyme')
	return {
		name: 'copy-to-plugins',
		setup(build) {
			build.onEnd(async () => {
				const sourceDir = process.cwd()
				const filesToCopy = ['main.js', 'manifest.json', 'styles.css']
				await fs.promises.mkdir(destDir, { recursive: true })
				for (const file of filesToCopy) {
					const src = path.join(sourceDir, file)
					const dst = path.join(destDir, file)
					try {
						await fs.promises.copyFile(src, dst)
					} catch (err) {
						if (file !== 'styles.css') console.error(`Error copying ${file}: ${err}`)
					}
				}
				console.log('Files copied to plugins directory')
			})
		}
	}
}

const context = await esbuild.context({
	platform: 'node',
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [copyToPluginsPlugin()]
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
