site_name: Reason Docs
site_author: Joshua Pham
site_url: https://jshph.github.io/obsidian-reason/
site_description: REASON - a plugin for Obsidian that Retrieves, Extracts, And Synthesizes Obsidian Notes.
repo_name: jshph/obsidian-reason
repo_url: https://github.com/jshph/obsidian-reason
theme:
  name: material
  font:
    text: Lato

  palette:
    - scheme: default
      primary: light-green
      accent: brown
  logo: assets/tree.svg
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - navigation.top
nav:
  - ✏️ Getting Started: index.md
  - ⛏️ Extraction Strategies: extraction-strategies.md
  - 💡 Examples: sample-aggregators.md
  - 🚧 Contributing: contributing/contributing.md

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy; 2023 <a href="https://jpham.space" style="color:#6d6dd4">Joshua Pham</a>
extra_css:
  - assets/style.css
